### ISSUE TITLE
Podman roadmap to stable

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#1778]
## Podman roadmap to stable

Currently, Podman provider is set as Experimental, mainly because of subtle differences with Docker that breaks some of the features.

To fix this, KIND implements an interface, so providers can diverge in their implementation maintaining its compatibility at the user level.

In order to move to stable the provider it has to have exactly the same capabilities that the Docker provider.

These are the work items I have identified:

- [x] Implement CI. This runs every night from the KIND master branch testing IPv4, IPv6 single and multinode clusters with HA.
https://github.com/aojea/kind/actions?query=workflow%3APodman
- [ ] Podman networking, this is a topic where podman deviates completely from docker, it's a long history, libnetwork vs CNI. Since 0.8.0 KIND moved to their own bridge, this is missing in podman yet, assign @aojea 
- [ ] Load docker images, this needs further discussion https://github.com/kubernetes-sigs/kind/pull/1766
- ...

**Comment by aojea** [comment]
/area provider/podman
/cc @amwat 

For those interested please report the missing features that you find

**Comment by amwat** [comment]
This looks great!
Also we should definitely try to see if we can get those github actions running upstream. 
thoughts @BenTheElder ?

**Comment by BenTheElder** [comment]
I'm in favor of this.

**Comment by afbjorklund** [comment]
>  Windows, Mac support (I do not know if this is even possible

It is _possible_, but you would have to manage the VM yourself since podman only supports a "remote" and not a integrated solution

There are also lots of question marks when it comes to port mapping and such, so thinking of dropping the feature from minikube:

https://github.com/kubernetes/minikube/issues/8003

Right now we are pinning 1.9.3, due to the 2.0.x bugs

**Comment by BenTheElder** [comment]
I don't think we should worry about windows / Mac for now.

We're supporting 2.X in kind 0.8

**Comment by afbjorklund** [comment]
Our issues with podman 2.x was mostly about `podman-remote`

The podman driver (for minikube) is more or less back now,
but we will probably support both of them for a while (2020)

We are hoping that most of the worst regressions are fixed in 2.1

**Comment by aojea** [comment]
here we go https://github.com/containers/podman/pull/8143

**Comment by afbjorklund** [comment]
I have added a similar story for minikube, we are hoping for podman v3....

https://github.com/kubernetes/minikube/issues/10237

**Comment by BenTheElder** [comment]
I expect revamped image loading to land in v0.11.0 (just started the cycle for that), I'm not sure we should block on windows / mac support.

We also have some limited CI for podman now, which is good.
