### ISSUE TITLE
[meta]: v0.11.0 priority tracking

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#2024]
For v0.11.0 we want to try something new to help keep our releases on track and communicate expectations better; this issue will track explicitly the priorities maintainers are aiming at for v0.11.0.

1. @BenTheElder, @munnerz: The first thing is actually going to ship as the last v0.10.0 "feature" but we haven't mentioned it publicly yet and it's relevant here: We need to expand the maintainer set. As such we've talked to our top 2 contributors that do not currently have maintainer level permissions (@aojea, @amwat) – we'll be adding them as maintainers to better ensure continuous maintenance and approval bandwidth, etc. 

2. @aojea, @BenTheElder: landing dual-stack support. #1275 #692 

3. @BenTheElder: General v1alpha5 config improvements: https://github.com/kubernetes-sigs/kind/issues/2023

4. @BenTheElder, @munnerz: multi-arch images built from releases, general overhaul of node image building, xref #381 #166 #2020

5. Additionally, once #4 lands @BenTheElder is interested in fully automating node image pushes, but this isn't a release blocker. Also xref #1895 

6. @aojea, @amwat, @munnerz: Ensure someone else cuts the v0.11.0 release, so we know the project has strong continuity in place. So far @BenTheElder has cut all releases, this time someone else will cut the release just so we can be sure the permissions and knowledge are indeed in place. We will continue to rotate this in the future. See also: # 1 on this list.

TODO:
- [ ] Set an optimistic due-date for the v0.11.0 milestone
- [x] Triage milestone issues
- [x] # 1 above
- [x] # 2 above
~- [ ] # 3 above~ Punted to v0.12.0 or later. Not enough time, excess time spent on CI health and support issues.
- [x] # 4 above
~- [ ] # 5 above~ Punted, not enough time.
- [ ] # 6 above

We will post updates back here tracking progress on these priorities.

**NOTE**: This is a combination of things we'll be building ourselves, helping review and merge, and otherwise generally prioritizing. It does NOT mean that no other changes can merge or that we're exclusively working on them, many of these things _already_ have PRs open from other contributors. This just means the maintainers aim to _prioritize_ work, reviews, etc. for these changes before we cut another release. As usual if things are taking too long we may go ahead and cut v0.11.0 before landing all of them, and other work will certainly happen as well. We'll still be putting things into [the milestone](https://github.com/kubernetes-sigs/kind/milestone/14), but this list gives an idea what we're putting the most effort towards.

**Comment by BenTheElder** [comment]
\# 1 progress: 

- [x] add to OWNERS for kind repo root https://github.com/kubernetes-sigs/kind/pull/2025
- [x] invite to owners for https://github.com/kind-ci/
- [ ] peribolos PR to add to repo administrators for kind repo
- [ ] docker registry access
- [ ] github.com/kubernetes/k8s.io GCB/GCS/GCR access for kind subproject
- [x] github.com/kubernetes/test-infra [OWNERS for kind repo jobs](https://github.com/kubernetes/test-infra/blob/87000a67b95a66a63a5665a4c686e981fe4bc33c/config/jobs/kubernetes-sigs/kind/OWNERS#L9-L14
)
- [ ] access to @kind-ci-robot account

**Comment by aojea** [comment]
I've updated https://github.com/kubernetes-sigs/kind/pull/692, since 1.21 will have the feature gate enabled by default we only need kindnet to support dual stack, and a new option to the ipFamily field

**Comment by BenTheElder** [comment]
dualstack landed though we have some follow up to do #2172

**Comment by damemi** [comment]
Hi, is there an estimate for the timeline of the 0.11 release? I know there have been some unexpected issues but from the checklist above it seems like it is a ways off.

We are holding our own release of Descheduler until we can update our CI to run on a 1.21 Kind cluster. Just checking if we should continue that or look into alternative CI options in the meantime

**Comment by BenTheElder** [comment]
We're not going to complete this whole checklist. 
1, 2 are done.
3, 5 are punted for sure. We will do the API updates next cycle and punt automation for a bit due to low bandwith and surpises coming up like https://github.com/kubernetes/kubernetes/issues/101275
4 is almost done, holding things up
6. will happen during the release

You can run 1.21 from an unreleased binary, or we'll have one O(soon). The PR for 4 is all but done I think. It needs another review pass, and it needs the push-node script update to combine each cross compiled image into a multi-arch image and push it. The latter shouldn't take long. The former depends on when other maintainers have time.

There's such high demand for this one, we want to release with it. It's also worth noting that Kubernetes's latest versions are not good with kind, they have a substantial startup time increase. We've been trying to make sure that gets fixed, and while the patches have landed, they're not in released versions yet. So 1.20.2 is the latest version we can safely ship by default.
The next round of patch releases for kubernetes are in a few weeks.

**Comment by BenTheElder** [comment]
I had a few other things going on today myself, but the key reason we've not released today is https://github.com/kind-ci/containerd-nightlies/issues/19

runc rc93 has a regression we're currently shipping @ HEAD that we thought we'd already moved past by upgrading containerd, but didn't actually pickup due to the bug above. 

That should be resolved after re-running the build with the linked patch there, and then updating the kind images. After that we should be pretty clear to release.

https://github.com/kubernetes-sigs/kind/issues/2236 is concerning for non-systemd hosts, but there's no actionable root cause yet and we expect most container hosts will be running systemd, so no plan to block on that.

We'll circle back on the API changes. I think they still make sense, but they cannot block the rest.

**Comment by BenTheElder** [comment]
er and #4 is now done, as of friday last week.

**Comment by BenTheElder** [comment]
I fixed the rc94 situation and that's merged now, @amwat is starting the process /  # 6.

**Comment by aojea** [comment]
mission accomplished :clap: 
/close
