### ISSUE TITLE
tracking: switch default branch to main

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#2120]
see: https://k8s.dev/rename, https://github.com/kubernetes/org/issues/2222

Checklist below added from https://github.com/kubernetes/community/commit/198374dd9147981e561ed99d0e1453189343999f

## Prerequisites

- [x] Ensure that your repo has low PR volume (<20 open PRs) and
less number of periodic jobs. The branch rename will re-trigger
prow on _all_ open PRs, which will cause a huge spike in the CI load.
  - We have zero periodic jobs directly consuming this repo
  - We have < 10 PRs open now (17:14 PST 2021-03-15)

- [x] Create an issue in your repo to track the branch rename.
You can paste this checklist in the issue body.
  - This is the issue

- [x] If you are not a root approver for the repo, assign a root
approver for approval.
  - I am a root approver

- [x] Once the issue has been approved, send a notice to your SIG's
mailing list about the potential branch rename.
  - Notice here: https://groups.google.com/g/kubernetes-sig-testing/c/Gi0A_TJsP7A

## Changes pre-rename

Make the following changes _before_ renaming the branch the `master` branch.

Note: There might be additional changes required that have not been
covered in this checklist.

### Anytime

These changes are **non-disruptive**  and can be made anytime before
renaming the branch.

- [x] If a prowjob triggers on the `master` branch (`branches` field
of the prowjob), add the `main` branch to the list
(see [kubernetes/test-infra#20665] for an example).

  - N/A: we only use one branch and don't specify it wherever possible

- [x] If the [`milestone_applier`] prow config references the `master` branch,
add the `main` branch to the config (see [kubernetes/test-infra#20675] for an example).

  - N/A: we don't use milestone applier

- [x] If the [`branch_protection`] prow config references the `master` branch,
add the `main` branch to the config.

  - N/A: we only use the automatic branch protection based on prowjobs

### Just before rename

These changes are **disruptive** and should be made just before
renaming the branch.

- [x] If a prowjob mentions the `master` branch in `base_ref`,
update it to the `main` branch. For a periodic job, ensure that
the branch is renamed between periodic job runs.
    - N/A we have no jobs that mention branches of this repo.

- [x] If a prowjob mentions `master` in its name, rename the job to
to not include the branch name. [`status-reconciler`] should automatically
migrate the PR status contexts to the new job name but this has not been tested yet.
The job with the new name will also appear as a different job in Testgrid.
   - N/A we have no jobs that mention branches of this repo.

- [x] If a prowjob calls scripts or code in your repo that explicitly
reference `master`, update all references to use `main`.
    - N/A we don't do this.

- [x] If the repo has netlify configured for it, ask a member of the GitHub
Management Team to rename the `master` branch to `main` in the netlify site config.
It can't be controlled through the netlify config in the repo.
  - We will need to do this.
  - This is done.

### Approval

- [x] Once all non-disruptive tasks have been completed and disruptive tasks
have been identified, assign the GitHub Management team ([@kubernetes/owners])
for approval.
  - https://github.com/kubernetes-sigs/kind/issues/2120#issuecomment-800675859 (see below)

## Rename the default branch

- [x] Rename the default branch from `master` to `main` using the GitHub UI
by following the [official instructions].

## Changes post-rename

After the default branch has been renamed to `main`, make the following
changes.

Note: There might be additional changes required that have not been
covered in this checklist.

### Prowjobs

- [x] If a prowjob still references the `master` branch in the `branches` field,
remove the `master` branch (see [kubernetes/test-infra#20669] for an example).
  - N/A we have no jobs that mention branches of this repo.

### Prow config

- [x] If the [`milestone_applier`] prow config references the `master` branch,
remove it from the config.
  - N/A we don't use milestone_applier here

- [x] If the [`branch_protection`] prow config references the `master` branch,
remove it from the config.
  - N/A we don't have any repo specific branch_protection config (just the automated standard configuration)

### Other

- [x] If any docs reference the `master` branch, update to `main`
(URLs will be automatically redirected).
  - This is done.

- [x] Ensure that CI and PR tests work fine.
  - Look fine so far.

- [x] Trial the local development experience with a pre-rename clone.
  - Nothing in our development experience is branch specific, I just needed to switch from master to main as expected.

- [x] Send a notice about the branch rename to your SIG's mailing list.
Include the link to the [GitHub instructions to rename your local branch].

/assign

**Comment by BenTheElder** [comment]
went through the current checklist, discussing some feedback in slack here: https://kubernetes.slack.com/archives/C1TU9EB9S/p1615487742145000

**Comment by BenTheElder** [comment]
will follow up further next week (I am unavailable friday, and it seems best to not try to switch this on a friday anyhow)

**Comment by BenTheElder** [comment]
Went through the checklist.

We need to send the mailinglist notice, and we'll need help from GitHub management to update Netlify. The rest should be fine.

Will aim to do this Tomorrow.

**Comment by BenTheElder** [comment]
Reached out to @kubernetes/owners in #github-management slack https://kubernetes.slack.com/archives/C01672LSZL0/p1615931201001700

**Comment by spiffxp** [comment]
Ah right. Different org

**Comment by BenTheElder** [comment]
> /assign @kubernetes/owners

This is one of the things I have in https://github.com/kubernetes/community/issues/5636, that's not possible.

**Comment by BenTheElder** [comment]
Cleaned up references in https://github.com/kubernetes-sigs/kind/pull/2137. After merge we can see https://kind.sigs.k8s.io/ is at https://github.com/kubernetes-sigs/kind/commit/b30f419467bec22e0331887c4e07717da9db6861 so the netlify settings worked as well.

**Comment by BenTheElder** [comment]
Left some more feedback https://github.com/kubernetes/community/issues/5636#issuecomment-800682619

And updated the mailinglist. This is done. Thanks all.
