### ISSUE TITLE
setup new repo

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#4]
- [x] transfer history from [kubernetes/test-infra/kind](https://github.com/kubernetes/test-infra/tree/master/kind) - https://github.com/kubernetes-sigs/kind/pull/1
- [x] setup `dep` / vendor deps - https://github.com/kubernetes-sigs/kind/pull/2
- [x] setup scripts for managing deps and `BUILD` files -  https://github.com/kubernetes-sigs/kind/pull/3
- [x] setup `WORKSPACE` / fix `bazel build //:kind` - https://github.com/kubernetes-sigs/kind/pull/3
- [ ] ~setup guides for development and contributing~ moved to https://github.com/kubernetes-sigs/kind/issues/78, https://github.com/kubernetes-sigs/kind/issues/79
- [x] file issues with and without help-wanted [WIP], see #5, #6, ...
- [x] point old location to this repo - https://github.com/kubernetes/test-infra/pull/9382 
- [x] add presubmits [kubernetes/test-infra#9409](https://github.com/kubernetes/test-infra/pull/9409)  [kubernetes/test-infra#9410](https://github.com/kubernetes/test-infra/pull/9410) [kubernetes/test-infra#9591](https://github.com/kubernetes/test-infra/pull/9591)

/assign

**Comment by BenTheElder** [comment]
Closing this out, moved usage / developer guides to their own tracking issues
