### ISSUE TITLE
Support ignite

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#705]
**What would you like to be added**: Support for using `ignite` as a docker-like backend with improved isolation. 

**Why is this needed**: This provides a relatively fast but much more isolated option for nodes. On the surface the UX is very similar to the docker CLI, and it operates around standard docker images, with the requirement that you use an `/sbin/init` (which we do, though wrapped for docker in docker workarounds).

Some thoughts:
- This likely wouldn't ever support `extraMounts` (or any mounts for that matter, firecracker doesn't support this). It might however support some form of persistent storage in the future, which we'd want to consider how to support as well... https://github.com/weaveworks/ignite/issues/76
- We'll probably want to resolve the following issues upstream first:
  - [ ] https://github.com/weaveworks/ignite/issues/164 Missing `/etc/resolv.conf` (we could work around this ourselves easily, but probably upstream will want to do something as well)
  - [ ] https://github.com/weaveworks/ignite/issues/142 support configuring listen address and protocol (we don't _need_ this, but it would bring the port forwarding up to parity)
  - [ ] https://github.com/weaveworks/ignite/issues/65 Consider adding `ignite exec [vm] [command]` (we either need this, or we need to implement something similar with either attach or ssh, it would be least leaky to just implement exec upstream if they're willing, I reached out...)
- I already intend to decouple the internals of kind from docker better (and in fact, am working on that right now...) to support a mock node provider and podman, adding `ignite` seems like a natural next step, and will cause us to think a little more about things that are not exactly docker.

/priority backlog
/assign

**Comment by aojea** [comment]
Just for clarification, the goal is to replace current provider or to allow kind to use multiple providers?
By the way, I was able to play with ignite and sounds and awesome idea, this also allow to test different kernels , ...

**Comment by BenTheElder** [comment]
Definitely not replace (!) There's too many environments that won't have access to this, realistically, and we have our existing users etc. 🙃

As an _additional_ backend this would be pretty useful and mostly can map pretty closely to what we do already 😁

**Comment by tao12345666333** [comment]
SGTM.
I think this will be fun.
The main reason for choosing `ignite` is due to its UX?

**Comment by danielfbm** [comment]
I am working to add `kubernetes` as a new provider (using kubectl to manage pods, etcs), is this a viable/desirable goal for `kind` ? If yes, I would like to contribute (and probably would need some guidance)

**Comment by BenTheElder** [comment]
Hi, I've actually already written this as a joke, it came up at our kubecon
deep dive too :+)

At this time we're not ready for that, it might be amusing someday, but we
aren't prepared to actually support it and wouldn't recommend it, and need
to land other changes.

**Comment by danielfbm** [comment]
Could you kindly share the code if possible? In our team kind fits as a
perfect development environment, but not really possible to run directly
from our laptops, so considering a kubernetes cluster to handle the
orchestration seems fair.
Thanks

**Comment by BenTheElder** [comment]
it's not in a good state, however there are many comments here about running kind in kubernetes clusters :grimacing: 

I highly recommend avoiding that if at all possible, it's tricky to avoid the various footguns, in general I don't recommend creating priviliged containers in kubernetes clusters unless you are working on a system component like kube-proxy.

**Comment by danielfbm** [comment]
that is our main issue. Our team is mostly working with operators/CRDS/aggregations and the need to share resources (cluster of servers) is big deal for us, so we are willing to give it a shot to avoid creating another orchestration tool 😅, but really appreciate the heads up.

I looked through most of the issues that reference this kind of use case, I think #303 is the most important one here and I will post the issues I found there if it is ok for you.

**Comment by BenTheElder** [comment]
I don't recommend it, unfortunately we must do it anyhow. This is all deeply on my backlog, currently focused on some kubernetes testing needs and https://github.com/kubernetes-sigs/kind/issues/148
